 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TPeriod } from './Period';

export type TAccountGuarantor = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  party: TReference;
  onHold?: boolean;
  period?: TPeriod;
};
