 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TInt } from '../simpleTypes/Int';

export type TAccountCoverage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  coverage: TReference;
  priority?: TInt;
};
