 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TExpression } from './Expression';

export type TActivityDefinitionDynamicValue = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  path: string;
  expression: TExpression;
};
