 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TAdministrableProductDefinitionWithdrawalPeriod } from './AdministrableProductDefinitionWithdrawalPeriod';

export type TAdministrableProductDefinitionTargetSpecies = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  withdrawalPeriod?: TAdministrableProductDefinitionWithdrawalPeriod[];
};
