 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRatio } from './Ratio';
import { TAdministrableProductDefinitionTargetSpecies } from './AdministrableProductDefinitionTargetSpecies';

export type TAdministrableProductDefinitionRouteOfAdministration = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  firstDose?: TQuantity;
  maxSingleDose?: TQuantity;
  maxDosePerDay?: TQuantity;
  maxDosePerTreatmentPeriod?: TRatio;
  maxTreatmentPeriod?: TQuantity;
  targetSpecies?: TAdministrableProductDefinitionTargetSpecies[];
};
