 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TAdverseEventCausality } from './AdverseEventCausality';

export type TAdverseEventSuspectEntity = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  instance: TReference;
  causality?: TAdverseEventCausality[];
};
