 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TAdverseEventCausality = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  assessment?: TCodeableConcept;
  productRelatedness?: string;
  author?: TReference;
  method?: TCodeableConcept;
};
