 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TAnnotation } from './Annotation';

export type TAllergyIntoleranceReaction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  substance?: TCodeableConcept;
  manifestation: TCodeableConcept[];
  description?: string;
  onset?: TDateTime;
  severity?: string;
  exposureRoute?: TCodeableConcept;
  note?: TAnnotation[];
};
