 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TPeriod } from './Period';

export type TAppointmentParticipant = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept[];
  actor?: TReference;
  required?: string;
  status: string;
  period?: TPeriod;
};
