 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TUri } from '../simpleTypes/Uri';
import { TCoding } from './Coding';
import { TAuditEventNetwork } from './AuditEventNetwork';

export type TAuditEventAgent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  role?: TCodeableConcept[];
  who?: TReference;
  altId?: string;
  name?: string;
  requestor: boolean;
  location?: TReference;
  policy?: TUri[];
  media?: TCoding;
  network?: TAuditEventNetwork;
  purposeOfUse?: TCodeableConcept[];
};
