 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCoding } from './Coding';

export type TAuditEventSource = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  site?: string;
  observer: TReference;
  type?: TCoding[];
};
