 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TAuditEventNetwork = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  address?: string;
  type?: string;
};
