 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';

export type TBiologicallyDerivedProductCollection = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  collector?: TReference;
  source?: TReference;
  collectedDateTime?: TDateTime;
  collectedPeriod?: TPeriod;
};
