 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';

export type TBiologicallyDerivedProductProcessing = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  procedure?: TCodeableConcept;
  additive?: TReference;
  timeDateTime?: TDateTime;
  timePeriod?: TPeriod;
};
