 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';

export type TBiologicallyDerivedProductManipulation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  timeDateTime?: TDateTime;
  timePeriod?: TPeriod;
};
