 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TCapabilityStatementSecurity } from './CapabilityStatementSecurity';
import { TCapabilityStatementResource } from './CapabilityStatementResource';
import { TCapabilityStatementInteraction1 } from './CapabilityStatementInteraction1';
import { TCapabilityStatementSearchParam } from './CapabilityStatementSearchParam';
import { TCapabilityStatementOperation } from './CapabilityStatementOperation';
import { TCanonical } from '../simpleTypes/Canonical';

export type TCapabilityStatementRest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  mode: string;
  documentation?: TMarkdown;
  security?: TCapabilityStatementSecurity;
  resource?: TCapabilityStatementResource[];
  interaction?: TCapabilityStatementInteraction1[];
  searchParam?: TCapabilityStatementSearchParam[];
  operation?: TCapabilityStatementOperation[];
  compartment?: TCanonical[];
};
