 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TCapabilityStatementSecurity = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  cors?: boolean;
  service?: TCodeableConcept[];
  description?: TMarkdown;
};
