 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCapabilityStatementEndpoint } from './CapabilityStatementEndpoint';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TCapabilityStatementSupportedMessage } from './CapabilityStatementSupportedMessage';

export type TCapabilityStatementMessaging = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  endpoint?: TCapabilityStatementEndpoint[];
  reliableCache?: TUnsignedInt;
  documentation?: TMarkdown;
  supportedMessage?: TCapabilityStatementSupportedMessage[];
};
