 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TUrl } from '../simpleTypes/Url';

export type TCapabilityStatementEndpoint = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  protocol: TCoding;
  address: TUrl;
};
