 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TPeriod } from './Period';

export type TCareTeamParticipant = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role?: TCodeableConcept[];
  member?: TReference;
  onBehalfOf?: TReference;
  period?: TPeriod;
};
