 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TAnnotation } from './Annotation';
import { TCarePlanDetail } from './CarePlanDetail';

export type TCarePlanActivity = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  outcomeCodeableConcept?: TCodeableConcept[];
  outcomeReference?: TReference[];
  progress?: TAnnotation[];
  reference?: TReference;
  detail?: TCarePlanDetail;
};
