 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TUri } from '../simpleTypes/Uri';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TTiming } from './Timing';
import { TPeriod } from './Period';
import { TQuantity } from './Quantity';

export type TCarePlanDetail = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  kind?: string;
  instantiatesCanonical?: TCanonical[];
  instantiatesUri?: TUri[];
  code?: TCodeableConcept;
  reasonCode?: TCodeableConcept[];
  reasonReference?: TReference[];
  goal?: TReference[];
  status: string;
  statusReason?: TCodeableConcept;
  doNotPerform?: boolean;
  scheduledTiming?: TTiming;
  scheduledPeriod?: TPeriod;
  scheduledString?: string;
  location?: TReference;
  performer?: TReference[];
  productCodeableConcept?: TCodeableConcept;
  productReference?: TReference;
  dailyAmount?: TQuantity;
  quantity?: TQuantity;
  description?: string;
};
