 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TChargeItemDefinitionApplicability } from './ChargeItemDefinitionApplicability';
import { TChargeItemDefinitionPriceComponent } from './ChargeItemDefinitionPriceComponent';

export type TChargeItemDefinitionPropertyGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  applicability?: TChargeItemDefinitionApplicability[];
  priceComponent?: TChargeItemDefinitionPriceComponent[];
};
