 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TCitationVersion } from './CitationVersion';
import { TCodeableConcept } from './CodeableConcept';
import { TCitationStatusDate1 } from './CitationStatusDate1';
import { TCitationTitle } from './CitationTitle';
import { TCitationAbstract } from './CitationAbstract';
import { TCitationPart } from './CitationPart';
import { TCitationRelatesTo1 } from './CitationRelatesTo1';
import { TCitationPublicationForm } from './CitationPublicationForm';
import { TCitationWebLocation } from './CitationWebLocation';
import { TCitationClassification1 } from './CitationClassification1';
import { TCitationContributorship } from './CitationContributorship';
import { TAnnotation } from './Annotation';

export type TCitationCitedArtifact = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  relatedIdentifier?: TIdentifier[];
  dateAccessed?: TDateTime;
  version?: TCitationVersion;
  currentState?: TCodeableConcept[];
  statusDate?: TCitationStatusDate1[];
  title?: TCitationTitle[];
  abstract?: TCitationAbstract[];
  part?: TCitationPart;
  relatesTo?: TCitationRelatesTo1[];
  publicationForm?: TCitationPublicationForm[];
  webLocation?: TCitationWebLocation[];
  classification?: TCitationClassification1[];
  contributorship?: TCitationContributorship;
  note?: TAnnotation[];
};
