 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TIdentifier } from './Identifier';
import { TReference } from './Reference';

export type TCitationPublishedIn = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  identifier?: TIdentifier[];
  title?: string;
  publisher?: TReference;
  publisherLocation?: string;
};
