 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TCitationWhoClassified } from './CitationWhoClassified';

export type TCitationClassification1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  classifier?: TCodeableConcept[];
  whoClassified?: TCitationWhoClassified;
};
