 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';

export type TCitationAffiliationInfo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  affiliation?: string;
  role?: string;
  identifier?: TIdentifier[];
};
