 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';

export type TCitationStatusDate1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  activity: TCodeableConcept;
  actual?: boolean;
  period: TPeriod;
};
