 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TCitationAbstract = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  language?: TCodeableConcept;
  text: TMarkdown;
  copyright?: TMarkdown;
};
