 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCitationEntry } from './CitationEntry';
import { TCitationSummary1 } from './CitationSummary1';

export type TCitationContributorship = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  complete?: boolean;
  entry?: TCitationEntry[];
  summary?: TCitationSummary1[];
};
