 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { THumanName } from './HumanName';
import { TIdentifier } from './Identifier';
import { TCitationAffiliationInfo } from './CitationAffiliationInfo';
import { TAddress } from './Address';
import { TContactPoint } from './ContactPoint';
import { TCodeableConcept } from './CodeableConcept';
import { TCitationContributionInstance } from './CitationContributionInstance';
import { TInt } from '../simpleTypes/Int';

export type TCitationEntry = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: THumanName;
  initials?: string;
  collectiveName?: string;
  identifier?: TIdentifier[];
  affiliationInfo?: TCitationAffiliationInfo[];
  address?: TAddress[];
  telecom?: TContactPoint[];
  contributionType?: TCodeableConcept[];
  role?: TCodeableConcept;
  contributionInstance?: TCitationContributionInstance[];
  correspondingContact?: boolean;
  listOrder?: TInt;
};
