 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TCitationDateOfPublication } from './CitationDateOfPublication';

export type TCitationPeriodicRelease = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  citedMedium?: TCodeableConcept;
  volume?: string;
  issue?: string;
  dateOfPublication?: TCitationDateOfPublication;
};
