 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TUri } from '../simpleTypes/Uri';
import { TIdentifier } from './Identifier';
import { TReference } from './Reference';
import { TAttachment } from './Attachment';

export type TCitationRelatesTo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  relationshipType: TCodeableConcept;
  targetClassifier?: TCodeableConcept[];
  targetUri?: TUri;
  targetIdentifier?: TIdentifier;
  targetReference?: TReference;
  targetAttachment?: TAttachment;
};
