 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';

export type TClaimResponseProcessNote = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  number?: TInt;
  type?: string;
  text: string;
  language?: TCodeableConcept;
};
