 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TClaimResponseAdjudication } from './ClaimResponseAdjudication';
import { TClaimResponseSubDetail } from './ClaimResponseSubDetail';

export type TClaimResponseDetail = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  detailSequence: TInt;
  noteNumber?: TInt[];
  adjudication: TClaimResponseAdjudication[];
  subDetail?: TClaimResponseSubDetail[];
};
