 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TClaimDiagnosis = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  diagnosisCodeableConcept?: TCodeableConcept;
  diagnosisReference?: TReference;
  type?: TCodeableConcept[];
  onAdmission?: TCodeableConcept;
  packageCode?: TCodeableConcept;
};
