 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from './Period';
import { TQuantity } from './Quantity';
import { TAttachment } from './Attachment';
import { TReference } from './Reference';

export type TClaimSupportingInfo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  category: TCodeableConcept;
  code?: TCodeableConcept;
  timingDate?: TDate;
  timingPeriod?: TPeriod;
  valueBoolean?: boolean;
  valueString?: string;
  valueQuantity?: TQuantity;
  valueAttachment?: TAttachment;
  valueReference?: TReference;
  reason?: TCodeableConcept;
};
