 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMoney } from './Money';
import { TDate } from '../simpleTypes/Date';
import { TIdentifier } from './Identifier';

export type TClaimResponsePayment = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  adjustment?: TMoney;
  adjustmentReason?: TCodeableConcept;
  date?: TDate;
  amount: TMoney;
  identifier?: TIdentifier;
};
