 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from './Period';
import { TAddress } from './Address';
import { TReference } from './Reference';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';
import { TClaimDetail } from './ClaimDetail';

export type TClaimItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  careTeamSequence?: TInt[];
  diagnosisSequence?: TInt[];
  procedureSequence?: TInt[];
  informationSequence?: TInt[];
  revenue?: TCodeableConcept;
  category?: TCodeableConcept;
  productOrService: TCodeableConcept;
  modifier?: TCodeableConcept[];
  programCode?: TCodeableConcept[];
  servicedDate?: TDate;
  servicedPeriod?: TPeriod;
  locationCodeableConcept?: TCodeableConcept;
  locationAddress?: TAddress;
  locationReference?: TReference;
  quantity?: TQuantity;
  unitPrice?: TMoney;
  factor?: TDecimal;
  net?: TMoney;
  udi?: TReference[];
  bodySite?: TCodeableConcept;
  subSite?: TCodeableConcept[];
  encounter?: TReference[];
  detail?: TClaimDetail[];
};
