 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';
import { TInt } from '../simpleTypes/Int';
import { TClaimResponseAdjudication } from './ClaimResponseAdjudication';

export type TClaimResponseSubDetail1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  productOrService: TCodeableConcept;
  modifier?: TCodeableConcept[];
  quantity?: TQuantity;
  unitPrice?: TMoney;
  factor?: TDecimal;
  net?: TMoney;
  noteNumber?: TInt[];
  adjudication: TClaimResponseAdjudication[];
};
