 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDate } from '../simpleTypes/Date';
import { TCodeableConcept } from './CodeableConcept';
import { TAddress } from './Address';
import { TReference } from './Reference';

export type TClaimAccident = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  date: TDate;
  type?: TCodeableConcept;
  locationAddress?: TAddress;
  locationReference?: TReference;
};
