 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TClaimCareTeam = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  provider: TReference;
  responsible?: boolean;
  role?: TCodeableConcept;
  qualification?: TCodeableConcept;
};
