 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';
import { TReference } from './Reference';
import { TClaimSubDetail } from './ClaimSubDetail';

export type TClaimDetail = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  revenue?: TCodeableConcept;
  category?: TCodeableConcept;
  productOrService: TCodeableConcept;
  modifier?: TCodeableConcept[];
  programCode?: TCodeableConcept[];
  quantity?: TQuantity;
  unitPrice?: TMoney;
  factor?: TDecimal;
  net?: TMoney;
  udi?: TReference[];
  subDetail?: TClaimSubDetail[];
};
