 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';

export type TClaimResponseError = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  itemSequence?: TInt;
  detailSequence?: TInt;
  subDetailSequence?: TInt;
  code: TCodeableConcept;
};
