 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TClaimResponseAdjudication } from './ClaimResponseAdjudication';
import { TClaimResponseDetail } from './ClaimResponseDetail';

export type TClaimResponseItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  itemSequence: TInt;
  noteNumber?: TInt[];
  adjudication: TClaimResponseAdjudication[];
  detail?: TClaimResponseDetail[];
};
