 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TIdentifier } from './Identifier';

export type TClaimRelated = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  claim?: TReference;
  relationship?: TCodeableConcept;
  reference?: TIdentifier;
};
