 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TCodeableReference } from './CodeableReference';

export type TClinicalUseDefinitionOtherTherapy = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  relationshipType: TCodeableConcept;
  therapy: TCodeableReference;
};
