 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TRange } from './Range';
import { TReference } from './Reference';
import { TClinicalUseDefinitionOtherTherapy } from './ClinicalUseDefinitionOtherTherapy';

export type TClinicalUseDefinitionIndication = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  diseaseSymptomProcedure?: TCodeableReference;
  diseaseStatus?: TCodeableReference;
  comorbidity?: TCodeableReference[];
  intendedEffect?: TCodeableReference;
  durationRange?: TRange;
  durationString?: string;
  undesirableEffect?: TReference[];
  otherTherapy?: TClinicalUseDefinitionOtherTherapy[];
};
