 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TCodeableConcept } from './CodeableConcept';

export type TClinicalUseDefinitionWarning = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: TMarkdown;
  code?: TCodeableConcept;
};
