 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TClinicalUseDefinitionInteractant } from './ClinicalUseDefinitionInteractant';
import { TCodeableConcept } from './CodeableConcept';
import { TCodeableReference } from './CodeableReference';

export type TClinicalUseDefinitionInteraction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  interactant?: TClinicalUseDefinitionInteractant[];
  type?: TCodeableConcept;
  effect?: TCodeableReference;
  incidence?: TCodeableConcept;
  management?: TCodeableConcept[];
};
