 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TClinicalUseDefinitionInteractant = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  itemReference?: TReference;
  itemCodeableConcept?: TCodeableConcept;
};
