 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TReference } from './Reference';
import { TClinicalUseDefinitionOtherTherapy } from './ClinicalUseDefinitionOtherTherapy';

export type TClinicalUseDefinitionContraindication = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  diseaseSymptomProcedure?: TCodeableReference;
  diseaseStatus?: TCodeableReference;
  comorbidity?: TCodeableReference[];
  indication?: TReference[];
  otherTherapy?: TClinicalUseDefinitionOtherTherapy[];
};
