 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeSystemDesignation } from './CodeSystemDesignation';
import { TCodeSystemProperty1 } from './CodeSystemProperty1';

export type TCodeSystemConcept = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  display?: string;
  definition?: string;
  designation?: TCodeSystemDesignation[];
  property?: TCodeSystemProperty1[];
  concept?: TCodeSystemConcept[];
};
