 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';
import { TReference } from './Reference';

export type TCompositionEvent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept[];
  period?: TPeriod;
  detail?: TReference[];
};
