 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TReference } from './Reference';

export type TCompositionRelatesTo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  targetIdentifier?: TIdentifier;
  targetReference?: TReference;
};
