 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TUri } from '../simpleTypes/Uri';
import { TConceptMapElement } from './ConceptMapElement';
import { TConceptMapUnmapped } from './ConceptMapUnmapped';

export type TConceptMapGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  source?: TUri;
  sourceVersion?: string;
  target?: TUri;
  targetVersion?: string;
  element: TConceptMapElement[];
  unmapped?: TConceptMapUnmapped;
};
