 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TConceptMapTarget } from './ConceptMapTarget';

export type TConceptMapElement = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: string;
  display?: string;
  target?: TConceptMapTarget[];
};
