 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TPeriod } from './Period';
import { TConsentActor } from './ConsentActor';
import { TCodeableConcept } from './CodeableConcept';
import { TCoding } from './Coding';
import { TConsentData } from './ConsentData';

export type TConsentProvision = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: string;
  period?: TPeriod;
  actor?: TConsentActor[];
  action?: TCodeableConcept[];
  securityLabel?: TCoding[];
  purpose?: TCoding[];
  class_?: TCoding[];
  code?: TCodeableConcept[];
  dataPeriod?: TPeriod;
  data?: TConsentData[];
  provision?: TConsentProvision[];
};
