 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TConsentData = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  meaning: string;
  reference: TReference;
};
