 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TConsentActor = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role: TCodeableConcept;
  reference: TReference;
};
