 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAttachment } from './Attachment';
import { TReference } from './Reference';

export type TContractRule = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  contentAttachment?: TAttachment;
  contentReference?: TReference;
};
