 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TReference } from './Reference';
import { TSignature } from './Signature';

export type TContractSigner = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCoding;
  party: TReference;
  signature: TSignature[];
};
