 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TIdentifier } from './Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TContractValuedItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  entityCodeableConcept?: TCodeableConcept;
  entityReference?: TReference;
  identifier?: TIdentifier;
  effectiveTime?: TDateTime;
  quantity?: TQuantity;
  unitPrice?: TMoney;
  factor?: TDecimal;
  points?: TDecimal;
  net?: TMoney;
  payment?: string;
  paymentDate?: TDateTime;
  responsible?: TReference;
  recipient?: TReference;
  linkId?: string[];
  securityLabelNumber?: TUnsignedInt[];
};
