 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TCoding } from './Coding';
import { TContractContext } from './ContractContext';
import { TPeriod } from './Period';
import { TContractAnswer } from './ContractAnswer';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TContractValuedItem } from './ContractValuedItem';

export type TContractAsset = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  scope?: TCodeableConcept;
  type?: TCodeableConcept[];
  typeReference?: TReference[];
  subtype?: TCodeableConcept[];
  relationship?: TCoding;
  context?: TContractContext[];
  condition?: string;
  periodType?: TCodeableConcept[];
  period?: TPeriod[];
  usePeriod?: TPeriod[];
  text?: string;
  linkId?: string[];
  answer?: TContractAnswer[];
  securityLabelNumber?: TUnsignedInt[];
  valuedItem?: TContractValuedItem[];
};
