 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TContactDetail } from './ContactDetail';

export type TContributor = {
  id?: string;
  extension?: TExtension[];
  type: string;
  name: string;
  contact?: TContactDetail[];
};
