 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TContractSubject = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  reference: TReference[];
  role?: TCodeableConcept;
};
