 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TContractParty } from './ContractParty';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TContractAnswer } from './ContractAnswer';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TContractOffer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  party?: TContractParty[];
  topic?: TReference;
  type?: TCodeableConcept;
  decision?: TCodeableConcept;
  decisionMode?: TCodeableConcept[];
  answer?: TContractAnswer[];
  text?: string;
  linkId?: string[];
  securityLabelNumber?: TUnsignedInt[];
};
