 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TCoding } from './Coding';

export type TContractSecurityLabel = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  number?: TUnsignedInt[];
  classification: TCoding;
  category?: TCoding[];
  control?: TCoding[];
};
