 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TContractSecurityLabel } from './ContractSecurityLabel';
import { TContractOffer } from './ContractOffer';
import { TContractAsset } from './ContractAsset';
import { TContractAction } from './ContractAction';

export type TContractTerm = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  issued?: TDateTime;
  applies?: TPeriod;
  topicCodeableConcept?: TCodeableConcept;
  topicReference?: TReference;
  type?: TCodeableConcept;
  subType?: TCodeableConcept;
  text?: string;
  securityLabel?: TContractSecurityLabel[];
  offer: TContractOffer;
  asset?: TContractAsset[];
  action?: TContractAction[];
  group?: TContractTerm[];
};
