 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDecimal } from '../simpleTypes/Decimal';
import { TInt } from '../simpleTypes/Int';
import { TDate } from '../simpleTypes/Date';
import { TDateTime } from '../simpleTypes/DateTime';
import { TTime } from '../simpleTypes/Time';
import { TUri } from '../simpleTypes/Uri';
import { TAttachment } from './Attachment';
import { TCoding } from './Coding';
import { TQuantity } from './Quantity';
import { TReference } from './Reference';

export type TContractAnswer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  valueBoolean?: boolean;
  valueDecimal?: TDecimal;
  valueInteger?: TInt;
  valueDate?: TDate;
  valueDateTime?: TDateTime;
  valueTime?: TTime;
  valueString?: string;
  valueUri?: TUri;
  valueAttachment?: TAttachment;
  valueCoding?: TCoding;
  valueQuantity?: TQuantity;
  valueReference?: TReference;
};
