 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TContractContext = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  reference?: TReference;
  code?: TCodeableConcept[];
  text?: string;
};
