 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';

export type TCoverageException = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  period?: TPeriod;
};
