 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TCoverageEligibilityRequestDiagnosis = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  diagnosisCodeableConcept?: TCodeableConcept;
  diagnosisReference?: TReference;
};
