 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TReference } from './Reference';

export type TCoverageEligibilityRequestSupportingInfo = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  information: TReference;
  appliesToAll?: boolean;
};
