 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TCoverageException } from './CoverageException';

export type TCoverageCostToBeneficiary = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  valueQuantity?: TQuantity;
  valueMoney?: TMoney;
  exception?: TCoverageException[];
};
