 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TCoverageEligibilityRequestInsurance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  focal?: boolean;
  coverage: TReference;
  businessArrangement?: string;
};
