 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TCoverageEligibilityRequestDiagnosis } from './CoverageEligibilityRequestDiagnosis';

export type TCoverageEligibilityRequestItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  supportingInfoSequence?: TInt[];
  category?: TCodeableConcept;
  productOrService?: TCodeableConcept;
  modifier?: TCodeableConcept[];
  provider?: TReference;
  quantity?: TQuantity;
  unitPrice?: TMoney;
  facility?: TReference;
  diagnosis?: TCoverageEligibilityRequestDiagnosis[];
  detail?: TReference[];
};
