 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TCoverageClass = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  value: string;
  name?: string;
};
