 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TPeriod } from './Period';
import { TCoverageEligibilityResponseItem } from './CoverageEligibilityResponseItem';

export type TCoverageEligibilityResponseInsurance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  coverage: TReference;
  inforce?: boolean;
  benefitPeriod?: TPeriod;
  item?: TCoverageEligibilityResponseItem[];
};
