 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCoding } from './Coding';

export type TDataRequirementCodeFilter = {
  id?: string;
  extension?: TExtension[];
  path?: string;
  searchParam?: string;
  valueSet?: TCanonical;
  code?: TCoding[];
};
