 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TDataRequirementCodeFilter } from './DataRequirementCodeFilter';
import { TDataRequirementDateFilter } from './DataRequirementDateFilter';
import { TInt } from '../simpleTypes/Int';
import { TDataRequirementSort } from './DataRequirementSort';

export type TDataRequirement = {
  id?: string;
  extension?: TExtension[];
  type: string;
  profile?: TCanonical[];
  subjectCodeableConcept?: TCodeableConcept;
  subjectReference?: TReference;
  mustSupport?: string[];
  codeFilter?: TDataRequirementCodeFilter[];
  dateFilter?: TDataRequirementDateFilter[];
  limit?: TInt;
  sort?: TDataRequirementSort[];
};
