 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from './Reference';

export type TDetectedIssueMitigation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  action: TCodeableConcept;
  date?: TDateTime;
  author?: TReference;
};
