 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TDeviceSpecialization = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  systemType: TCodeableConcept;
  version?: string;
};
