 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TDeviceDefinitionMaterial = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  substance: TCodeableConcept;
  alternate?: boolean;
  allergenicIndicator?: boolean;
};
