 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAttachment } from './Attachment';
import { TCoding } from './Coding';

export type TDocumentReferenceContent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  attachment: TAttachment;
  format?: TCoding;
};
