 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TReference } from './Reference';

export type TDocumentManifestRelated = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  ref?: TReference;
};
