 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';

export type TDocumentReferenceContext = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  encounter?: TReference[];
  event?: TCodeableConcept[];
  period?: TPeriod;
  facilityType?: TCodeableConcept;
  practiceSetting?: TCodeableConcept;
  sourcePatientInfo?: TReference;
  related?: TReference[];
};
