 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TTiming } from './Timing';
import { TDosageDoseAndRate } from './DosageDoseAndRate';
import { TRatio } from './Ratio';
import { TQuantity } from './Quantity';

export type TDosage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence?: TInt;
  text?: string;
  additionalInstruction?: TCodeableConcept[];
  patientInstruction?: string;
  timing?: TTiming;
  asNeededBoolean?: boolean;
  asNeededCodeableConcept?: TCodeableConcept;
  site?: TCodeableConcept;
  route?: TCodeableConcept;
  method?: TCodeableConcept;
  doseAndRate?: TDosageDoseAndRate[];
  maxDosePerPeriod?: TRatio;
  maxDosePerAdministration?: TQuantity;
  maxDosePerLifetime?: TQuantity;
};
