 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TRange } from './Range';
import { TQuantity } from './Quantity';
import { TRatio } from './Ratio';

export type TDosageDoseAndRate = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  doseRange?: TRange;
  doseQuantity?: TQuantity;
  rateRatio?: TRatio;
  rateRange?: TRange;
  rateQuantity?: TQuantity;
};
