 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TEncounterHospitalization = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  preAdmissionIdentifier?: TIdentifier;
  origin?: TReference;
  admitSource?: TCodeableConcept;
  reAdmission?: TCodeableConcept;
  dietPreference?: TCodeableConcept[];
  specialCourtesy?: TCodeableConcept[];
  specialArrangement?: TCodeableConcept[];
  destination?: TReference;
  dischargeDisposition?: TCodeableConcept;
};
