 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TPeriod } from './Period';

export type TEncounterClassHistory = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  class_: TCoding;
  period: TPeriod;
};
