 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';

export type TEncounterLocation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  location: TReference;
  status?: string;
  physicalType?: TCodeableConcept;
  period?: TPeriod;
};
