 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';

export type TEpisodeOfCareDiagnosis = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  condition: TReference;
  role?: TCodeableConcept;
  rank?: TInt;
};
