 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAnnotation } from './Annotation';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TDecimal } from '../simpleTypes/Decimal';
import { TRange } from './Range';

export type TEvidenceAttributeEstimate = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  note?: TAnnotation[];
  type?: TCodeableConcept;
  quantity?: TQuantity;
  level?: TDecimal;
  range?: TRange;
  attributeEstimate?: TEvidenceAttributeEstimate[];
};
