 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';
import { TRange } from './Range';
import { TAnnotation } from './Annotation';

export type TEvidenceVariableTimeFromStart = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  quantity?: TQuantity;
  range?: TRange;
  note?: TAnnotation[];
};
