 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRange } from './Range';

export type TEvidenceVariableCategory = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  valueCodeableConcept?: TCodeableConcept;
  valueQuantity?: TQuantity;
  valueRange?: TRange;
};
