 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TEvidenceVariable } from './EvidenceVariable';
import { TEvidenceAttributeEstimate } from './EvidenceAttributeEstimate';

export type TEvidenceModelCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  value?: TQuantity;
  variable?: TEvidenceVariable[];
  attributeEstimate?: TEvidenceAttributeEstimate[];
};
