 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCodeableConcept } from './CodeableConcept';
import { TExpression } from './Expression';
import { TEvidenceVariableTimeFromStart } from './EvidenceVariableTimeFromStart';

export type TEvidenceVariableCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  definitionReference?: TReference;
  definitionCanonical?: TCanonical;
  definitionCodeableConcept?: TCodeableConcept;
  definitionExpression?: TExpression;
  method?: TCodeableConcept;
  device?: TReference;
  exclude?: boolean;
  timeFromStart?: TEvidenceVariableTimeFromStart;
  groupMeasure?: string;
};
