 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRange } from './Range';

export type TEvidenceVariable = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  variableDefinition: TReference;
  handling?: string;
  valueCategory?: TCodeableConcept[];
  valueQuantity?: TQuantity[];
  valueRange?: TRange[];
};
