 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TEvidenceReportCharacteristic } from './EvidenceReportCharacteristic';
import { TAnnotation } from './Annotation';

export type TEvidenceReportSubject = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  characteristic?: TEvidenceReportCharacteristic[];
  note?: TAnnotation[];
};
