 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TQuantity } from './Quantity';
import { TRange } from './Range';
import { TPeriod } from './Period';

export type TEvidenceReportCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  valueReference?: TReference;
  valueCodeableConcept?: TCodeableConcept;
  valueBoolean?: boolean;
  valueQuantity?: TQuantity;
  valueRange?: TRange;
  exclude?: boolean;
  period?: TPeriod;
};
