 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAnnotation } from './Annotation';
import { TCodeableConcept } from './CodeableConcept';

export type TEvidenceCertainty = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  note?: TAnnotation[];
  type?: TCodeableConcept;
  rating?: TCodeableConcept;
  rater?: string;
  subcomponent?: TEvidenceCertainty[];
};
