 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TAnnotation } from './Annotation';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TEvidenceVariableDefinition = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: TMarkdown;
  note?: TAnnotation[];
  variableRole: TCodeableConcept;
  observed?: TReference;
  intended?: TReference;
  directnessMatch?: TCodeableConcept;
};
