 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAnnotation } from './Annotation';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TEvidenceSampleSize } from './EvidenceSampleSize';
import { TEvidenceAttributeEstimate } from './EvidenceAttributeEstimate';
import { TEvidenceModelCharacteristic } from './EvidenceModelCharacteristic';

export type TEvidenceStatistic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  note?: TAnnotation[];
  statisticType?: TCodeableConcept;
  category?: TCodeableConcept;
  quantity?: TQuantity;
  numberOfEvents?: TUnsignedInt;
  numberAffected?: TUnsignedInt;
  sampleSize?: TEvidenceSampleSize;
  attributeEstimate?: TEvidenceAttributeEstimate[];
  modelCharacteristic?: TEvidenceModelCharacteristic[];
};
