 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TNarrative } from './Narrative';
import { TQuantity } from './Quantity';

export type TEvidenceReportSection = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  title?: string;
  focus?: TCodeableConcept;
  focusReference?: TReference;
  author?: TReference[];
  text?: TNarrative;
  mode?: string;
  orderedBy?: TCodeableConcept;
  entryClassifier?: TCodeableConcept[];
  entryReference?: TReference[];
  entryQuantity?: TQuantity[];
  emptyReason?: TCodeableConcept;
  section?: TEvidenceReportSection[];
};
