 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TAnnotation } from './Annotation';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';

export type TEvidenceSampleSize = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  description?: string;
  note?: TAnnotation[];
  numberOfStudies?: TUnsignedInt;
  numberOfParticipants?: TUnsignedInt;
  knownDataCount?: TUnsignedInt;
};
