 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TExampleScenarioVersion } from './ExampleScenarioVersion';
import { TExampleScenarioContainedInstance } from './ExampleScenarioContainedInstance';

export type TExampleScenarioInstance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  resourceId: string;
  resourceType: string;
  name?: string;
  description?: TMarkdown;
  version?: TExampleScenarioVersion[];
  containedInstance?: TExampleScenarioContainedInstance[];
};
