 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TExampleScenarioProcess } from './ExampleScenarioProcess';
import { TExampleScenarioOperation } from './ExampleScenarioOperation';
import { TExampleScenarioAlternative } from './ExampleScenarioAlternative';

export type TExampleScenarioStep = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  process?: TExampleScenarioProcess[];
  pause?: boolean;
  operation?: TExampleScenarioOperation;
  alternative?: TExampleScenarioAlternative[];
};
