 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TExampleScenarioStep } from './ExampleScenarioStep';

export type TExampleScenarioProcess = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  title: string;
  description?: TMarkdown;
  preConditions?: TMarkdown;
  postConditions?: TMarkdown;
  step?: TExampleScenarioStep[];
};
