 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TExplanationOfBenefitInsurance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  focal: boolean;
  coverage: TReference;
  preAuthRef?: string[];
};
