 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TMoney } from './Money';

export type TExplanationOfBenefitFinancial = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  allowedUnsignedInt?: TUnsignedInt;
  allowedString?: string;
  allowedMoney?: TMoney;
  usedUnsignedInt?: TUnsignedInt;
  usedMoney?: TMoney;
};
