 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from './Reference';

export type TExplanationOfBenefitProcedure = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence: TInt;
  type?: TCodeableConcept[];
  date?: TDateTime;
  procedureCodeableConcept?: TCodeableConcept;
  procedureReference?: TReference;
  udi?: TReference[];
};
