 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';

export type TExplanationOfBenefitAdjudication = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category: TCodeableConcept;
  reason?: TCodeableConcept;
  amount?: TMoney;
  value?: TDecimal;
};
