 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TDate } from '../simpleTypes/Date';
import { TPeriod } from './Period';
import { TAddress } from './Address';
import { TQuantity } from './Quantity';
import { TMoney } from './Money';
import { TDecimal } from '../simpleTypes/Decimal';
import { TExplanationOfBenefitAdjudication } from './ExplanationOfBenefitAdjudication';
import { TExplanationOfBenefitDetail1 } from './ExplanationOfBenefitDetail1';

export type TExplanationOfBenefitAddItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  itemSequence?: TInt[];
  detailSequence?: TInt[];
  subDetailSequence?: TInt[];
  provider?: TReference[];
  productOrService: TCodeableConcept;
  modifier?: TCodeableConcept[];
  programCode?: TCodeableConcept[];
  servicedDate?: TDate;
  servicedPeriod?: TPeriod;
  locationCodeableConcept?: TCodeableConcept;
  locationAddress?: TAddress;
  locationReference?: TReference;
  quantity?: TQuantity;
  unitPrice?: TMoney;
  factor?: TDecimal;
  net?: TMoney;
  bodySite?: TCodeableConcept;
  subSite?: TCodeableConcept[];
  noteNumber?: TInt[];
  adjudication?: TExplanationOfBenefitAdjudication[];
  detail?: TExplanationOfBenefitDetail1[];
};
