 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TExplanationOfBenefitFinancial } from './ExplanationOfBenefitFinancial';

export type TExplanationOfBenefitBenefitBalance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category: TCodeableConcept;
  excluded?: boolean;
  name?: string;
  description?: string;
  network?: TCodeableConcept;
  unit?: TCodeableConcept;
  term?: TCodeableConcept;
  financial?: TExplanationOfBenefitFinancial[];
};
