 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRange } from './Range';
import { TPeriod } from './Period';
import { TAnnotation } from './Annotation';

export type TFamilyMemberHistoryCondition = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  outcome?: TCodeableConcept;
  contributedToDeath?: boolean;
  onsetAge?: TQuantity;
  onsetRange?: TRange;
  onsetPeriod?: TPeriod;
  onsetString?: string;
  note?: TAnnotation[];
};
