 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TPeriod } from './Period';

export type TGroupMember = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  entity: TReference;
  period?: TPeriod;
  inactive?: boolean;
};
