 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TPeriod } from './Period';

export type THumanName = {
  id?: string;
  extension?: TExtension[];
  use?: string;
  text?: string;
  family?: string;
  given?: string[];
  prefix?: string[];
  suffix?: string[];
  period?: TPeriod;
};
