 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TUri } from '../simpleTypes/Uri';
import { TPeriod } from './Period';
import { TReference } from './Reference';

export type TIdentifier = {
  id?: string;
  extension?: TExtension[];
  use?: string;
  type?: TCodeableConcept;
  system?: TUri;
  value?: string;
  period?: TPeriod;
  assigner?: TReference;
};
