 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';

export type TImmunizationProtocolApplied = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  series?: string;
  authority?: TReference;
  targetDisease?: TCodeableConcept[];
  doseNumberPositiveInt?: TInt;
  doseNumberString?: string;
  seriesDosesPositiveInt?: TInt;
  seriesDosesString?: string;
};
