 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from './Reference';

export type TImmunizationReaction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  date?: TDateTime;
  detail?: TReference;
  reported?: boolean;
};
