 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TUrl } from '../simpleTypes/Url';
import { TImplementationGuideResource1 } from './ImplementationGuideResource1';
import { TImplementationGuidePage1 } from './ImplementationGuidePage1';

export type TImplementationGuideManifest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  rendering?: TUrl;
  resource: TImplementationGuideResource1[];
  page?: TImplementationGuidePage1[];
  image?: string[];
  other?: string[];
};
