 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TImplementationGuideGrouping } from './ImplementationGuideGrouping';
import { TImplementationGuideResource } from './ImplementationGuideResource';
import { TImplementationGuidePage } from './ImplementationGuidePage';
import { TImplementationGuideParameter } from './ImplementationGuideParameter';
import { TImplementationGuideTemplate } from './ImplementationGuideTemplate';

export type TImplementationGuideDefinition = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  grouping?: TImplementationGuideGrouping[];
  resource: TImplementationGuideResource[];
  page?: TImplementationGuidePage;
  parameter?: TImplementationGuideParameter[];
  template?: TImplementationGuideTemplate[];
};
