 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TRatio } from './Ratio';
import { TRatioRange } from './RatioRange';
import { TCodeableConcept } from './CodeableConcept';
import { TIngredientReferenceStrength } from './IngredientReferenceStrength';

export type TIngredientStrength = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  presentationRatio?: TRatio;
  presentationRatioRange?: TRatioRange;
  textPresentation?: string;
  concentrationRatio?: TRatio;
  concentrationRatioRange?: TRatioRange;
  textConcentration?: string;
  measurementPoint?: string;
  country?: TCodeableConcept[];
  referenceStrength?: TIngredientReferenceStrength[];
};
