 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TIngredientStrength } from './IngredientStrength';

export type TIngredientSubstance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableReference;
  strength?: TIngredientStrength[];
};
