 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TRatio } from './Ratio';
import { TRatioRange } from './RatioRange';
import { TCodeableConcept } from './CodeableConcept';

export type TIngredientReferenceStrength = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  substance?: TCodeableReference;
  strengthRatio?: TRatio;
  strengthRatioRange?: TRatioRange;
  measurementPoint?: string;
  country?: TCodeableConcept[];
};
