 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';
import { TCodeableConcept } from './CodeableConcept';

export type TInsurancePlanLimit = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  value?: TQuantity;
  code?: TCodeableConcept;
};
