 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TInsurancePlanGeneralCost } from './InsurancePlanGeneralCost';
import { TInsurancePlanSpecificCost } from './InsurancePlanSpecificCost';

export type TInsurancePlanPlan = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  type?: TCodeableConcept;
  coverageArea?: TReference[];
  network?: TReference[];
  generalCost?: TInsurancePlanGeneralCost[];
  specificCost?: TInsurancePlanSpecificCost[];
};
