 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TInsurancePlanBenefit } from './InsurancePlanBenefit';

export type TInsurancePlanCoverage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  network?: TReference[];
  benefit: TInsurancePlanBenefit[];
};
