 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInsurancePlanCost } from './InsurancePlanCost';

export type TInsurancePlanBenefit1 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  cost?: TInsurancePlanCost[];
};
