 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInsurancePlanLimit } from './InsurancePlanLimit';

export type TInsurancePlanBenefit = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  requirement?: string;
  limit?: TInsurancePlanLimit[];
};
