 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInsurancePlanBenefit1 } from './InsurancePlanBenefit1';

export type TInsurancePlanSpecificCost = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category: TCodeableConcept;
  benefit?: TInsurancePlanBenefit1[];
};
