 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';
import { TMoney } from './Money';

export type TInsurancePlanGeneralCost = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  groupSize?: TInt;
  cost?: TMoney;
  comment?: string;
};
