 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { THumanName } from './HumanName';
import { TContactPoint } from './ContactPoint';
import { TAddress } from './Address';

export type TInsurancePlanContact = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  purpose?: TCodeableConcept;
  name?: THumanName;
  telecom?: TContactPoint[];
  address?: TAddress;
};
