 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TInvoicePriceComponent } from './InvoicePriceComponent';

export type TInvoiceLineItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  sequence?: TInt;
  chargeItemReference?: TReference;
  chargeItemCodeableConcept?: TCodeableConcept;
  priceComponent?: TInvoicePriceComponent[];
};
