 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDecimal } from '../simpleTypes/Decimal';
import { TMoney } from './Money';

export type TInvoicePriceComponent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: string;
  code?: TCodeableConcept;
  factor?: TDecimal;
  amount?: TMoney;
};
