 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TReference } from './Reference';

export type TListEntry = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  flag?: TCodeableConcept;
  deleted?: boolean;
  date?: TDateTime;
  item: TReference;
};
