 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TDate } from '../simpleTypes/Date';
import { TAttachment } from './Attachment';

export type TManufacturedItemDefinitionProperty = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  valueCodeableConcept?: TCodeableConcept;
  valueQuantity?: TQuantity;
  valueDate?: TDate;
  valueBoolean?: boolean;
  valueAttachment?: TAttachment;
};
