 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';
import { TDateTime } from '../simpleTypes/DateTime';

export type TMarketingStatus = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  country?: TCodeableConcept;
  jurisdiction?: TCodeableConcept;
  status: TCodeableConcept;
  dateRange?: TPeriod;
  restoreDate?: TDateTime;
};
