 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMeasureReportPopulation } from './MeasureReportPopulation';
import { TQuantity } from './Quantity';
import { TMeasureReportStratifier } from './MeasureReportStratifier';

export type TMeasureReportGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept;
  population?: TMeasureReportPopulation[];
  measureScore?: TQuantity;
  stratifier?: TMeasureReportStratifier[];
};
