 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';
import { TReference } from './Reference';

export type TMeasureReportPopulation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept;
  count?: TInt;
  subjectResults?: TReference;
};
