 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMeasurePopulation } from './MeasurePopulation';
import { TMeasureStratifier } from './MeasureStratifier';

export type TMeasureGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept;
  description?: string;
  population?: TMeasurePopulation[];
  stratifier?: TMeasureStratifier[];
};
