 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TExpression } from './Expression';
import { TMeasureComponent } from './MeasureComponent';

export type TMeasureStratifier = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept;
  description?: string;
  criteria?: TExpression;
  component?: TMeasureComponent[];
};
