 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMeasureReportComponent } from './MeasureReportComponent';
import { TMeasureReportPopulation1 } from './MeasureReportPopulation1';
import { TQuantity } from './Quantity';

export type TMeasureReportStratum = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  value?: TCodeableConcept;
  component?: TMeasureReportComponent[];
  population?: TMeasureReportPopulation1[];
  measureScore?: TQuantity;
};
