 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMeasureReportStratum } from './MeasureReportStratum';

export type TMeasureReportStratifier = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept[];
  stratum?: TMeasureReportStratum[];
};
