 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TCodeableConcept } from './CodeableConcept';

export type TMedicinalProductDefinitionCrossReference = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  product: TCodeableReference;
  type?: TCodeableConcept;
};
