 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TMedicationKnowledgeSubstitution } from './MedicationKnowledgeSubstitution';
import { TMedicationKnowledgeSchedule } from './MedicationKnowledgeSchedule';
import { TMedicationKnowledgeMaxDispense } from './MedicationKnowledgeMaxDispense';

export type TMedicationKnowledgeRegulatory = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  regulatoryAuthority: TReference;
  substitution?: TMedicationKnowledgeSubstitution[];
  schedule?: TMedicationKnowledgeSchedule[];
  maxDispense?: TMedicationKnowledgeMaxDispense;
};
