 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';

export type TMedicationKnowledgeMaxDispense = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  quantity: TQuantity;
  period?: TQuantity;
};
