 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMoney } from './Money';

export type TMedicationKnowledgeCost = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  source?: string;
  cost: TMoney;
};
