 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TPeriod } from './Period';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';

export type TMedicinalProductDefinitionOperation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableReference;
  effectiveDate?: TPeriod;
  organization?: TReference[];
  confidentialityIndicator?: TCodeableConcept;
};
