 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TMedicinalProductDefinitionNamePart } from './MedicinalProductDefinitionNamePart';
import { TMedicinalProductDefinitionCountryLanguage } from './MedicinalProductDefinitionCountryLanguage';

export type TMedicinalProductDefinitionName = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  productName: string;
  type?: TCodeableConcept;
  namePart?: TMedicinalProductDefinitionNamePart[];
  countryLanguage?: TMedicinalProductDefinitionCountryLanguage[];
};
