 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TMedicationDispenseSubstitution = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  wasSubstituted: boolean;
  type?: TCodeableConcept;
  reason?: TCodeableConcept[];
  responsibleParty?: TReference[];
};
