 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRatio } from './Ratio';

export type TMedicationAdministrationDosage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  text?: string;
  site?: TCodeableConcept;
  route?: TCodeableConcept;
  method?: TCodeableConcept;
  dose?: TQuantity;
  rateRatio?: TRatio;
  rateQuantity?: TQuantity;
};
