 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMedicationRequestInitialFill } from './MedicationRequestInitialFill';
import { TQuantity } from './Quantity';
import { TPeriod } from './Period';
import { TUnsignedInt } from '../simpleTypes/UnsignedInt';
import { TReference } from './Reference';

export type TMedicationRequestDispenseRequest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  initialFill?: TMedicationRequestInitialFill;
  dispenseInterval?: TQuantity;
  validityPeriod?: TPeriod;
  numberOfRepeatsAllowed?: TUnsignedInt;
  quantity?: TQuantity;
  expectedSupplyDuration?: TQuantity;
  performer?: TReference;
};
