 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';

export type TMedicationKnowledgePatientCharacteristics = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  characteristicCodeableConcept?: TCodeableConcept;
  characteristicQuantity?: TQuantity;
  value?: string[];
};
