 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TMedicationAdministrationPerformer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  function_?: TCodeableConcept;
  actor: TReference;
};
