 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMedicationKnowledgeDosage } from './MedicationKnowledgeDosage';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TMedicationKnowledgePatientCharacteristics } from './MedicationKnowledgePatientCharacteristics';

export type TMedicationKnowledgeAdministrationGuidelines = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  dosage?: TMedicationKnowledgeDosage[];
  indicationCodeableConcept?: TCodeableConcept;
  indicationReference?: TReference;
  patientCharacteristics?: TMedicationKnowledgePatientCharacteristics[];
};
