 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TRatio } from './Ratio';

export type TMedicationKnowledgeIngredient = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  itemCodeableConcept?: TCodeableConcept;
  itemReference?: TReference;
  isActive?: boolean;
  strength?: TRatio;
};
