 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TContactPoint } from './ContactPoint';
import { TUrl } from '../simpleTypes/Url';

export type TMessageHeaderSource = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  software?: string;
  version?: string;
  contact?: TContactPoint;
  endpoint: TUrl;
};
