 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TReference } from './Reference';

export type TMessageHeaderResponse = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier: TId;
  code: string;
  details?: TReference;
};
