 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TInstant } from '../simpleTypes/Instant';
import { TUri } from '../simpleTypes/Uri';
import { TCanonical } from '../simpleTypes/Canonical';
import { TCoding } from './Coding';

export type TMeta = {
  id?: string;
  extension?: TExtension[];
  versionId?: TId;
  lastUpdated?: TInstant;
  source?: TUri;
  profile?: TCanonical[];
  security?: TCoding[];
  tag?: TCoding[];
};
