 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';
import { TQuantity } from './Quantity';
import { TDecimal } from '../simpleTypes/Decimal';
import { TMolecularSequenceRoc } from './MolecularSequenceRoc';

export type TMolecularSequenceQuality = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: string;
  standardSequence?: TCodeableConcept;
  start?: TInt;
  end?: TInt;
  score?: TQuantity;
  method?: TCodeableConcept;
  truthTP?: TDecimal;
  queryTP?: TDecimal;
  truthFN?: TDecimal;
  queryFP?: TDecimal;
  gtFP?: TDecimal;
  precision?: TDecimal;
  recall?: TDecimal;
  fScore?: TDecimal;
  roc?: TMolecularSequenceRoc;
};
