 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TInt } from '../simpleTypes/Int';

export type TMolecularSequenceReferenceSeq = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  chromosome?: TCodeableConcept;
  genomeBuild?: string;
  orientation?: string;
  referenceSeqId?: TCodeableConcept;
  referenceSeqPointer?: TReference;
  referenceSeqString?: string;
  strand?: string;
  windowStart?: TInt;
  windowEnd?: TInt;
};
