 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';
import { TMolecularSequenceOuter } from './MolecularSequenceOuter';
import { TMolecularSequenceInner } from './MolecularSequenceInner';

export type TMolecularSequenceStructureVariant = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  variantType?: TCodeableConcept;
  exact?: boolean;
  length?: TInt;
  outer?: TMolecularSequenceOuter;
  inner?: TMolecularSequenceInner;
};
