 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDecimal } from '../simpleTypes/Decimal';

export type TMoney = {
  id?: string;
  extension?: TExtension[];
  value?: TDecimal;
  currency?: string;
};
