 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TNutritionOrderTexture = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  modifier?: TCodeableConcept;
  foodType?: TCodeableConcept;
};
