 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TRatio } from './Ratio';

export type TNutritionProductNutrient = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  item?: TCodeableReference;
  amount?: TRatio[];
};
