 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TTiming } from './Timing';
import { TQuantity } from './Quantity';

export type TNutritionOrderSupplement = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  productName?: string;
  schedule?: TTiming[];
  quantity?: TQuantity;
  instruction?: string;
};
