 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TTiming } from './Timing';
import { TNutritionOrderNutrient } from './NutritionOrderNutrient';
import { TNutritionOrderTexture } from './NutritionOrderTexture';

export type TNutritionOrderOralDiet = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept[];
  schedule?: TTiming[];
  nutrient?: TNutritionOrderNutrient[];
  texture?: TNutritionOrderTexture[];
  fluidConsistencyType?: TCodeableConcept[];
  instruction?: string;
};
