 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTiming } from './Timing';
import { TQuantity } from './Quantity';
import { TRatio } from './Ratio';

export type TNutritionOrderAdministration = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  schedule?: TTiming;
  quantity?: TQuantity;
  rateQuantity?: TQuantity;
  rateRatio?: TRatio;
};
