 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TBase64Binary } from '../simpleTypes/Base64Binary';
import { TAttachment } from './Attachment';

export type TNutritionProductProductCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: TCodeableConcept;
  valueCodeableConcept?: TCodeableConcept;
  valueString?: string;
  valueQuantity?: TQuantity;
  valueBase64Binary?: TBase64Binary;
  valueAttachment?: TAttachment;
  valueBoolean?: boolean;
};
