 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TInt } from '../simpleTypes/Int';
import { TRange } from './Range';
import { TRatio } from './Ratio';
import { TSampledData } from './SampledData';
import { TTime } from '../simpleTypes/Time';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';
import { TObservationReferenceRange } from './ObservationReferenceRange';

export type TObservationComponent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: TCodeableConcept;
  valueQuantity?: TQuantity;
  valueCodeableConcept?: TCodeableConcept;
  valueString?: string;
  valueBoolean?: boolean;
  valueInteger?: TInt;
  valueRange?: TRange;
  valueRatio?: TRatio;
  valueSampledData?: TSampledData;
  valueTime?: TTime;
  valueDateTime?: TDateTime;
  valuePeriod?: TPeriod;
  dataAbsentReason?: TCodeableConcept;
  interpretation?: TCodeableConcept[];
  referenceRange?: TObservationReferenceRange[];
};
