 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDecimal } from '../simpleTypes/Decimal';
import { TInt } from '../simpleTypes/Int';

export type TObservationDefinitionQuantitativeDetails = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  customaryUnit?: TCodeableConcept;
  unit?: TCodeableConcept;
  conversionFactor?: TDecimal;
  decimalPrecision?: TInt;
};
