 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';
import { TCodeableConcept } from './CodeableConcept';
import { TRange } from './Range';

export type TObservationReferenceRange = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  low?: TQuantity;
  high?: TQuantity;
  type?: TCodeableConcept;
  appliesTo?: TCodeableConcept[];
  age?: TRange;
  text?: string;
};
