 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TOperationOutcomeIssue = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  severity: string;
  code: string;
  details?: TCodeableConcept;
  diagnostics?: string;
  location?: string[];
  expression?: string[];
};
