 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableReference } from './CodeableReference';
import { TQuantity } from './Quantity';

export type TPackagedProductDefinitionContainedItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  item: TCodeableReference;
  amount?: TQuantity;
};
