 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';

export type TPackagedProductDefinitionShelfLifeStorage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  periodDuration?: TQuantity;
  periodString?: string;
  specialPrecautionsForStorage?: TCodeableConcept[];
};
