 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TInt } from '../simpleTypes/Int';
import { TPackagedProductDefinitionShelfLifeStorage } from './PackagedProductDefinitionShelfLifeStorage';
import { TReference } from './Reference';
import { TPackagedProductDefinitionProperty } from './PackagedProductDefinitionProperty';
import { TPackagedProductDefinitionContainedItem } from './PackagedProductDefinitionContainedItem';

export type TPackagedProductDefinitionPackage = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  type?: TCodeableConcept;
  quantity?: TInt;
  material?: TCodeableConcept[];
  alternateMaterial?: TCodeableConcept[];
  shelfLifeStorage?: TPackagedProductDefinitionShelfLifeStorage[];
  manufacturer?: TReference[];
  property?: TPackagedProductDefinitionProperty[];
  containedItem?: TPackagedProductDefinitionContainedItem[];
  package?: TPackagedProductDefinitionPackage[];
};
