 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TPatientLink = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  other: TReference;
  type: string;
};
