 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { THumanName } from './HumanName';
import { TContactPoint } from './ContactPoint';
import { TAddress } from './Address';
import { TReference } from './Reference';
import { TPeriod } from './Period';

export type TPatientContact = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  relationship?: TCodeableConcept[];
  name?: THumanName;
  telecom?: TContactPoint[];
  address?: TAddress;
  gender?: string;
  organization?: TReference;
  period?: TPeriod;
};
