 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TPatientCommunication = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  language: TCodeableConcept;
  preferred?: boolean;
};
