 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';
import { TDate } from '../simpleTypes/Date';
import { TMoney } from './Money';

export type TPaymentReconciliationDetail = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  predecessor?: TIdentifier;
  type: TCodeableConcept;
  request?: TReference;
  submitter?: TReference;
  response?: TReference;
  date?: TDate;
  responsible?: TReference;
  payee?: TReference;
  amount?: TMoney;
};
