 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TPersonLink = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  target: TReference;
  assurance?: string;
};
