 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TRelatedArtifact } from './RelatedArtifact';
import { TId } from '../simpleTypes/Id';
import { TReference } from './Reference';
import { TCanonical } from '../simpleTypes/Canonical';
import { TTriggerDefinition } from './TriggerDefinition';
import { TPlanDefinitionCondition } from './PlanDefinitionCondition';
import { TDataRequirement } from './DataRequirement';
import { TPlanDefinitionRelatedAction } from './PlanDefinitionRelatedAction';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from './Quantity';
import { TPeriod } from './Period';
import { TRange } from './Range';
import { TTiming } from './Timing';
import { TPlanDefinitionParticipant } from './PlanDefinitionParticipant';
import { TUri } from '../simpleTypes/Uri';
import { TPlanDefinitionDynamicValue } from './PlanDefinitionDynamicValue';

export type TPlanDefinitionAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  prefix?: string;
  title?: string;
  description?: string;
  textEquivalent?: string;
  priority?: string;
  code?: TCodeableConcept[];
  reason?: TCodeableConcept[];
  documentation?: TRelatedArtifact[];
  goalId?: TId[];
  subjectCodeableConcept?: TCodeableConcept;
  subjectReference?: TReference;
  subjectCanonical?: TCanonical;
  trigger?: TTriggerDefinition[];
  condition?: TPlanDefinitionCondition[];
  input?: TDataRequirement[];
  output?: TDataRequirement[];
  relatedAction?: TPlanDefinitionRelatedAction[];
  timingDateTime?: TDateTime;
  timingAge?: TQuantity;
  timingPeriod?: TPeriod;
  timingDuration?: TQuantity;
  timingRange?: TRange;
  timingTiming?: TTiming;
  participant?: TPlanDefinitionParticipant[];
  type?: TCodeableConcept;
  groupingBehavior?: string;
  selectionBehavior?: string;
  requiredBehavior?: string;
  precheckBehavior?: string;
  cardinalityBehavior?: string;
  definitionCanonical?: TCanonical;
  definitionUri?: TUri;
  transform?: TCanonical;
  dynamicValue?: TPlanDefinitionDynamicValue[];
  action?: TPlanDefinitionAction[];
};
