 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TRelatedArtifact } from './RelatedArtifact';
import { TPlanDefinitionTarget } from './PlanDefinitionTarget';

export type TPlanDefinitionGoal = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  category?: TCodeableConcept;
  description: TCodeableConcept;
  priority?: TCodeableConcept;
  start?: TCodeableConcept;
  addresses?: TCodeableConcept[];
  documentation?: TRelatedArtifact[];
  target?: TPlanDefinitionTarget[];
};
