 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRange } from './Range';

export type TPlanDefinitionTarget = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  measure?: TCodeableConcept;
  detailQuantity?: TQuantity;
  detailRange?: TRange;
  detailCodeableConcept?: TCodeableConcept;
  due?: TQuantity;
};
