 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TQuantity } from './Quantity';
import { TRange } from './Range';

export type TPlanDefinitionRelatedAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  actionId: TId;
  relationship: string;
  offsetDuration?: TQuantity;
  offsetRange?: TRange;
};
