 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TExpression } from './Expression';

export type TPlanDefinitionCondition = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  kind: string;
  expression?: TExpression;
};
