 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TRange } from './Range';
import { TCodeableConcept } from './CodeableConcept';

export type TPopulation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  ageRange?: TRange;
  ageCodeableConcept?: TCodeableConcept;
  gender?: TCodeableConcept;
  race?: TCodeableConcept;
  physiologicalCondition?: TCodeableConcept;
};
