 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';
import { TReference } from './Reference';

export type TPractitionerQualification = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  code: TCodeableConcept;
  period?: TPeriod;
  issuer?: TReference;
};
