 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';

export type TProductShelfLife = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  type: TCodeableConcept;
  period: TQuantity;
  specialPrecautionsForStorage?: TCodeableConcept[];
};
