 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';
import { TAttachment } from './Attachment';
import { TCodeableConcept } from './CodeableConcept';

export type TProdCharacteristic = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  height?: TQuantity;
  width?: TQuantity;
  depth?: TQuantity;
  weight?: TQuantity;
  nominalVolume?: TQuantity;
  externalDiameter?: TQuantity;
  shape?: string;
  color?: string[];
  imprint?: string[];
  image?: TAttachment[];
  scoring?: TCodeableConcept;
};
