 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TProvenanceAgent } from './ProvenanceAgent';

export type TProvenanceEntity = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role: string;
  what: TReference;
  agent?: TProvenanceAgent[];
};
