 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TDate } from '../simpleTypes/Date';
import { TTime } from '../simpleTypes/Time';
import { TCoding } from './Coding';
import { TReference } from './Reference';

export type TQuestionnaireAnswerOption = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  valueInteger?: TInt;
  valueDate?: TDate;
  valueTime?: TTime;
  valueString?: string;
  valueCoding?: TCoding;
  valueReference?: TReference;
  initialSelected?: boolean;
};
