 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDecimal } from '../simpleTypes/Decimal';
import { TInt } from '../simpleTypes/Int';
import { TDate } from '../simpleTypes/Date';
import { TDateTime } from '../simpleTypes/DateTime';
import { TTime } from '../simpleTypes/Time';
import { TCoding } from './Coding';
import { TQuantity } from './Quantity';
import { TReference } from './Reference';

export type TQuestionnaireEnableWhen = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  question: string;
  operator: string;
  answerBoolean?: boolean;
  answerDecimal?: TDecimal;
  answerInteger?: TInt;
  answerDate?: TDate;
  answerDateTime?: TDateTime;
  answerTime?: TTime;
  answerString?: string;
  answerCoding?: TCoding;
  answerQuantity?: TQuantity;
  answerReference?: TReference;
};
