 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';

export type TRange = {
  id?: string;
  extension?: TExtension[];
  low?: TQuantity;
  high?: TQuantity;
};
