 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';

export type TRatioRange = {
  id?: string;
  extension?: TExtension[];
  lowNumerator?: TQuantity;
  highNumerator?: TQuantity;
  denominator?: TQuantity;
};
