 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TPeriod } from './Period';
import { TDateTime } from '../simpleTypes/DateTime';

export type TRegulatedAuthorizationCase = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  type?: TCodeableConcept;
  status?: TCodeableConcept;
  datePeriod?: TPeriod;
  dateDateTime?: TDateTime;
  application?: TRegulatedAuthorizationCase[];
};
