 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TMarkdown } from '../simpleTypes/Markdown';
import { TUrl } from '../simpleTypes/Url';
import { TAttachment } from './Attachment';
import { TCanonical } from '../simpleTypes/Canonical';

export type TRelatedArtifact = {
  id?: string;
  extension?: TExtension[];
  type: string;
  label?: string;
  display?: string;
  citation?: TMarkdown;
  url?: TUrl;
  document?: TAttachment;
  resource?: TCanonical;
};
