 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TRelatedArtifact } from './RelatedArtifact';
import { TRequestGroupCondition } from './RequestGroupCondition';
import { TRequestGroupRelatedAction } from './RequestGroupRelatedAction';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from './Quantity';
import { TPeriod } from './Period';
import { TRange } from './Range';
import { TTiming } from './Timing';
import { TReference } from './Reference';

export type TRequestGroupAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  prefix?: string;
  title?: string;
  description?: string;
  textEquivalent?: string;
  priority?: string;
  code?: TCodeableConcept[];
  documentation?: TRelatedArtifact[];
  condition?: TRequestGroupCondition[];
  relatedAction?: TRequestGroupRelatedAction[];
  timingDateTime?: TDateTime;
  timingAge?: TQuantity;
  timingPeriod?: TPeriod;
  timingDuration?: TQuantity;
  timingRange?: TRange;
  timingTiming?: TTiming;
  participant?: TReference[];
  type?: TCodeableConcept;
  groupingBehavior?: string;
  selectionBehavior?: string;
  requiredBehavior?: string;
  precheckBehavior?: string;
  cardinalityBehavior?: string;
  resource?: TReference;
  action?: TRequestGroupAction[];
};
