 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDecimal } from '../simpleTypes/Decimal';
import { TRange } from './Range';
import { TPeriod } from './Period';

export type TRiskAssessmentPrediction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  outcome?: TCodeableConcept;
  probabilityDecimal?: TDecimal;
  probabilityRange?: TRange;
  qualitativeRisk?: TCodeableConcept;
  relativeRisk?: TDecimal;
  whenPeriod?: TPeriod;
  whenRange?: TRange;
  rationale?: string;
};
