 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TInstant } from '../simpleTypes/Instant';
import { TReference } from './Reference';
import { TBase64Binary } from '../simpleTypes/Base64Binary';

export type TSignature = {
  id?: string;
  extension?: TExtension[];
  type: TCoding[];
  when: TInstant;
  who: TReference;
  onBehalfOf?: TReference;
  targetFormat?: string;
  sigFormat?: string;
  data?: TBase64Binary;
};
