 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TSpecimenDefinitionAdditive } from './SpecimenDefinitionAdditive';

export type TSpecimenDefinitionContainer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  material?: TCodeableConcept;
  type?: TCodeableConcept;
  cap?: TCodeableConcept;
  description?: string;
  capacity?: TQuantity;
  minimumVolumeQuantity?: TQuantity;
  minimumVolumeString?: string;
  additive?: TSpecimenDefinitionAdditive[];
  preparation?: string;
};
