 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TSpecimenDefinitionContainer } from './SpecimenDefinitionContainer';
import { TQuantity } from './Quantity';
import { TSpecimenDefinitionHandling } from './SpecimenDefinitionHandling';

export type TSpecimenDefinitionTypeTested = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  isDerived?: boolean;
  type?: TCodeableConcept;
  preference: string;
  container?: TSpecimenDefinitionContainer;
  requirement?: string;
  retentionTime?: TQuantity;
  rejectionCriterion?: TCodeableConcept[];
  handling?: TSpecimenDefinitionHandling[];
};
