 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TRange } from './Range';
import { TQuantity } from './Quantity';

export type TSpecimenDefinitionHandling = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  temperatureQualifier?: TCodeableConcept;
  temperatureRange?: TRange;
  maxDuration?: TQuantity;
  instruction?: string;
};
