 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TDateTime } from '../simpleTypes/DateTime';
import { TPeriod } from './Period';
import { TQuantity } from './Quantity';
import { TCodeableConcept } from './CodeableConcept';

export type TSpecimenCollection = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  collector?: TReference;
  collectedDateTime?: TDateTime;
  collectedPeriod?: TPeriod;
  duration?: TQuantity;
  quantity?: TQuantity;
  method?: TCodeableConcept;
  bodySite?: TCodeableConcept;
  fastingStatusCodeableConcept?: TCodeableConcept;
  fastingStatusDuration?: TQuantity;
};
