 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TReference } from './Reference';

export type TSpecimenContainer = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier[];
  description?: string;
  type?: TCodeableConcept;
  capacity?: TQuantity;
  specimenQuantity?: TQuantity;
  additiveCodeableConcept?: TCodeableConcept;
  additiveReference?: TReference;
};
