 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TStructureDefinitionContext = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type: string;
  expression: string;
};
