 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TStructureMapInput } from './StructureMapInput';
import { TStructureMapRule } from './StructureMapRule';

export type TStructureMapGroup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: TId;
  extends_?: TId;
  typeMode: string;
  documentation?: string;
  input: TStructureMapInput[];
  rule: TStructureMapRule[];
};
