 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TStructureMapParameter } from './StructureMapParameter';

export type TStructureMapTarget = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  context?: TId;
  contextType?: string;
  element?: string;
  variable?: TId;
  listMode?: string[];
  listRuleId?: TId;
  transform?: string;
  parameter?: TStructureMapParameter[];
};
