 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TElementDefinition } from './ElementDefinition';

export type TStructureDefinitionSnapshot = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  element: TElementDefinition[];
};
