 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';
import { TStructureMapSource } from './StructureMapSource';
import { TStructureMapTarget } from './StructureMapTarget';
import { TStructureMapDependent } from './StructureMapDependent';

export type TStructureMapRule = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: TId;
  source: TStructureMapSource[];
  target?: TStructureMapTarget[];
  rule?: TStructureMapRule[];
  dependent?: TStructureMapDependent[];
  documentation?: string;
};
