 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TId } from '../simpleTypes/Id';

export type TStructureMapDependent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: TId;
  variable: string[];
};
