 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';

export type TSubstanceDefinitionOfficial = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  authority?: TCodeableConcept;
  status?: TCodeableConcept;
  date?: TDateTime;
};
