 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TSubscriptionTopicQueryCriteria = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  previous?: string;
  resultForCreate?: string;
  current?: string;
  resultForDelete?: string;
  requireBoth?: boolean;
};
