 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TIdentifier } from './Identifier';
import { TDateTime } from '../simpleTypes/DateTime';
import { TQuantity } from './Quantity';

export type TSubstanceInstance = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TIdentifier;
  expiry?: TDateTime;
  quantity?: TQuantity;
};
