 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TIdentifier } from './Identifier';
import { TQuantity } from './Quantity';

export type TSubstanceDefinitionMoiety = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  role?: TCodeableConcept;
  identifier?: TIdentifier;
  name?: string;
  stereochemistry?: TCodeableConcept;
  opticalActivity?: TCodeableConcept;
  molecularFormula?: string;
  amountQuantity?: TQuantity;
  amountString?: string;
  measurementType?: TCodeableConcept;
};
