 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRatio } from './Ratio';

export type TSubstanceDefinitionRelationship = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  substanceDefinitionReference?: TReference;
  substanceDefinitionCodeableConcept?: TCodeableConcept;
  type: TCodeableConcept;
  isDefining?: boolean;
  amountQuantity?: TQuantity;
  amountRatio?: TRatio;
  amountString?: string;
  ratioHighLimitAmount?: TRatio;
  comparator?: TCodeableConcept;
  source?: TReference[];
};
