 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TRatio } from './Ratio';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TSubstanceIngredient = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  quantity?: TRatio;
  substanceCodeableConcept?: TCodeableConcept;
  substanceReference?: TReference;
};
