 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';
import { TAnnotation } from './Annotation';
import { TReference } from './Reference';

export type TSubstanceDefinitionCode = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: TCodeableConcept;
  status?: TCodeableConcept;
  statusDate?: TDateTime;
  note?: TAnnotation[];
  source?: TReference[];
};
