 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInstant } from '../simpleTypes/Instant';
import { TReference } from './Reference';

export type TSubscriptionStatusNotificationEvent = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  eventNumber: string;
  timestamp?: TInstant;
  focus?: TReference;
  additionalContext?: TReference[];
};
