 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TSubstanceDefinitionOfficial } from './SubstanceDefinitionOfficial';
import { TReference } from './Reference';

export type TSubstanceDefinitionName = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name: string;
  type?: TCodeableConcept;
  status?: TCodeableConcept;
  preferred?: boolean;
  language?: TCodeableConcept[];
  domain?: TCodeableConcept[];
  jurisdiction?: TCodeableConcept[];
  synonym?: TSubstanceDefinitionName[];
  translation?: TSubstanceDefinitionName[];
  official?: TSubstanceDefinitionOfficial[];
  source?: TReference[];
};
