 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TSubstanceDefinitionMolecularWeight } from './SubstanceDefinitionMolecularWeight';
import { TReference } from './Reference';
import { TSubstanceDefinitionRepresentation } from './SubstanceDefinitionRepresentation';

export type TSubstanceDefinitionStructure = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  stereochemistry?: TCodeableConcept;
  opticalActivity?: TCodeableConcept;
  molecularFormula?: string;
  molecularFormulaByMoiety?: string;
  molecularWeight?: TSubstanceDefinitionMolecularWeight;
  technique?: TCodeableConcept[];
  sourceDocument?: TReference[];
  representation?: TSubstanceDefinitionRepresentation[];
};
