 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';

export type TSubstanceDefinitionSourceMaterial = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCodeableConcept;
  genus?: TCodeableConcept;
  species?: TCodeableConcept;
  part?: TCodeableConcept;
  countryOfOrigin?: TCodeableConcept[];
};
