 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TQuantity } from './Quantity';
import { TCodeableConcept } from './CodeableConcept';
import { TReference } from './Reference';

export type TSupplyDeliverySuppliedItem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  quantity?: TQuantity;
  itemCodeableConcept?: TCodeableConcept;
  itemReference?: TReference;
};
