 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TPeriod } from './Period';
import { TReference } from './Reference';

export type TTaskRestriction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  repetitions?: TInt;
  period?: TPeriod;
  recipient?: TReference[];
};
