 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TTerminologyCapabilitiesClosure = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  translation?: boolean;
};
