 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TTerminologyCapabilitiesTranslation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  needsMap: boolean;
};
