 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTerminologyCapabilitiesFilter } from './TerminologyCapabilitiesFilter';

export type TTerminologyCapabilitiesVersion = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code?: string;
  isDefault?: boolean;
  compositional?: boolean;
  language?: string[];
  filter?: TTerminologyCapabilitiesFilter[];
  property?: string[];
};
