 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCanonical } from '../simpleTypes/Canonical';
import { TTerminologyCapabilitiesVersion } from './TerminologyCapabilitiesVersion';

export type TTerminologyCapabilitiesCodeSystem = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  uri?: TCanonical;
  version?: TTerminologyCapabilitiesVersion[];
  subsumption?: boolean;
};
