 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';

export type TTerminologyCapabilitiesFilter = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  op: string[];
};
