 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTerminologyCapabilitiesParameter } from './TerminologyCapabilitiesParameter';
import { TMarkdown } from '../simpleTypes/Markdown';

export type TTerminologyCapabilitiesExpansion = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  hierarchical?: boolean;
  paging?: boolean;
  incomplete?: boolean;
  parameter?: TTerminologyCapabilitiesParameter[];
  textFilter?: TMarkdown;
};
