 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptOperation } from './TestScriptOperation';

export type TTestScriptAction2 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  operation: TTestScriptOperation;
};
