 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestReportOperation } from './TestReportOperation';

export type TTestReportAction2 = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  operation: TTestReportOperation;
};
