 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptAction1 } from './TestScriptAction1';

export type TTestScriptTest = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  name?: string;
  description?: string;
  action: TTestScriptAction1[];
};
