 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestReportOperation } from './TestReportOperation';
import { TTestReportAssert } from './TestReportAssert';

export type TTestReportAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  operation?: TTestReportOperation;
  assert?: TTestReportAssert;
};
