 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptOperation } from './TestScriptOperation';
import { TTestScriptAssert } from './TestScriptAssert';

export type TTestScriptAction = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  operation?: TTestScriptOperation;
  assert?: TTestScriptAssert;
};
