 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptAction } from './TestScriptAction';

export type TTestScriptSetup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  action: TTestScriptAction[];
};
