 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TInt } from '../simpleTypes/Int';
import { TCoding } from './Coding';

export type TTestScriptDestination = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  index: TInt;
  profile: TCoding;
};
