 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptLink } from './TestScriptLink';
import { TTestScriptCapability } from './TestScriptCapability';

export type TTestScriptMetadata = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  link?: TTestScriptLink[];
  capability: TTestScriptCapability[];
};
