 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TInt } from '../simpleTypes/Int';
import { TTestScriptRequestHeader } from './TestScriptRequestHeader';
import { TId } from '../simpleTypes/Id';

export type TTestScriptOperation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  type?: TCoding;
  resource?: string;
  label?: string;
  description?: string;
  accept?: string;
  contentType?: string;
  destination?: TInt;
  encodeRequestUrl: boolean;
  method?: string;
  origin?: TInt;
  params?: string;
  requestHeader?: TTestScriptRequestHeader[];
  requestId?: TId;
  responseId?: TId;
  sourceId?: TId;
  targetId?: TId;
  url?: string;
};
