 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';

export type TTestScriptFixture = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  autocreate: boolean;
  autodelete: boolean;
  resource?: TReference;
};
