 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestScriptAction2 } from './TestScriptAction2';

export type TTestScriptTeardown = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  action: TTestScriptAction2[];
};
