 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestReportAction } from './TestReportAction';

export type TTestReportSetup = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  action: TTestReportAction[];
};
