 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTestReportAction2 } from './TestReportAction2';

export type TTestReportTeardown = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  action: TTestReportAction2[];
};
