 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDateTime } from '../simpleTypes/DateTime';
import { TTimingRepeat } from './TimingRepeat';
import { TCodeableConcept } from './CodeableConcept';

export type TTiming = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  event?: TDateTime[];
  repeat?: TTimingRepeat;
  code?: TCodeableConcept;
};
