 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TTiming } from './Timing';
import { TReference } from './Reference';
import { TDate } from '../simpleTypes/Date';
import { TDateTime } from '../simpleTypes/DateTime';
import { TDataRequirement } from './DataRequirement';
import { TExpression } from './Expression';

export type TTriggerDefinition = {
  id?: string;
  extension?: TExtension[];
  type: string;
  name?: string;
  timingTiming?: TTiming;
  timingReference?: TReference;
  timingDate?: TDate;
  timingDateTime?: TDateTime;
  data?: TDataRequirement[];
  condition?: TExpression;
};
