 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCoding } from './Coding';
import { TCodeableConcept } from './CodeableConcept';
import { TQuantity } from './Quantity';
import { TRange } from './Range';
import { TReference } from './Reference';

export type TUsageContext = {
  id?: string;
  extension?: TExtension[];
  code: TCoding;
  valueCodeableConcept?: TCodeableConcept;
  valueQuantity?: TQuantity;
  valueRange?: TRange;
  valueReference?: TReference;
};
