 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TValueSetDesignation } from './ValueSetDesignation';

export type TValueSetConcept = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  code: string;
  display?: string;
  designation?: TValueSetDesignation[];
};
