 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TDate } from '../simpleTypes/Date';
import { TValueSetInclude } from './ValueSetInclude';

export type TValueSetCompose = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  lockedDate?: TDate;
  inactive?: boolean;
  include: TValueSetInclude[];
  exclude?: TValueSetInclude[];
};
