 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TUri } from '../simpleTypes/Uri';
import { TDateTime } from '../simpleTypes/DateTime';
import { TInt } from '../simpleTypes/Int';
import { TValueSetParameter } from './ValueSetParameter';
import { TValueSetContains } from './ValueSetContains';

export type TValueSetExpansion = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  identifier?: TUri;
  timestamp: TDateTime;
  total?: TInt;
  offset?: TInt;
  parameter?: TValueSetParameter[];
  contains?: TValueSetContains[];
};
