 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TDateTime } from '../simpleTypes/DateTime';

export type TVerificationResultPrimarySource = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  who?: TReference;
  type?: TCodeableConcept[];
  communicationMethod?: TCodeableConcept[];
  validationStatus?: TCodeableConcept;
  validationDate?: TDateTime;
  canPushUpdates?: TCodeableConcept;
  pushTypeAvailable?: TCodeableConcept[];
};
