 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TSignature } from './Signature';

export type TVerificationResultValidator = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  organization: TReference;
  identityCertificate?: string;
  attestationSignature?: TSignature;
};
