 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TReference } from './Reference';
import { TCodeableConcept } from './CodeableConcept';
import { TDate } from '../simpleTypes/Date';
import { TSignature } from './Signature';

export type TVerificationResultAttestation = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  who?: TReference;
  onBehalfOf?: TReference;
  communicationMethod?: TCodeableConcept;
  date?: TDate;
  sourceIdentityCertificate?: string;
  proxyIdentityCertificate?: string;
  proxySignature?: TSignature;
  sourceSignature?: TSignature;
};
