 
 
// This file is auto-generated by generate_types so do not edit manually

import { TExtension } from './Extension';
import { TCodeableConcept } from './CodeableConcept';
import { TDecimal } from '../simpleTypes/Decimal';
import { TInt } from '../simpleTypes/Int';
import { TVisionPrescriptionPrism } from './VisionPrescriptionPrism';
import { TQuantity } from './Quantity';
import { TAnnotation } from './Annotation';

export type TVisionPrescriptionLensSpecification = {
  id?: string;
  extension?: TExtension[];
  modifierExtension?: TExtension[];
  product: TCodeableConcept;
  eye: string;
  sphere?: TDecimal;
  cylinder?: TDecimal;
  axis?: TInt;
  prism?: TVisionPrescriptionPrism[];
  add?: TDecimal;
  power?: TDecimal;
  backCurve?: TDecimal;
  diameter?: TDecimal;
  duration?: TQuantity;
  color?: string;
  brand?: string;
  note?: TAnnotation[];
};
